//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamer
    {
        public int Id { get; set; }
        public string player1 { get; set; }
        public string player2 { get; set; }
        public string saved { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
