//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQGradeClass
    {
        public int Id { get; set; }
        public string LynQSchool { get; set; }
        public string StudClass { get; set; }
        public decimal LstValue { get; set; }
    }
}
