//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQTAd
    {
        public int Id { get; set; }
        public string AdId { get; set; }
        public string LynQITcategory { get; set; }
        public string LynQITName { get; set; }
        public string LynQITdesc { get; set; }
        public string LynQName { get; set; }
        public string LynQFname { get; set; }
        public string LynQimg { get; set; }
        public string LynQSchimg { get; set; }
        public string LynQProg { get; set; }
        public string LynQSch { get; set; }
        public string LynQITPrice { get; set; }
        public Nullable<int> LynQersInterested { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> DisLikes { get; set; }
        public string Likers { get; set; }
        public string Dislikers { get; set; }
        public string ITStatus { get; set; }
        public string Itemimg { get; set; }
        public Nullable<System.DateTime> AdDate { get; set; }
        public string LynQTphony { get; set; }
    }
}
