//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQInfoBoard
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string LynQName { get; set; }
        public string Scope { get; set; }
        public string Info { get; set; }
        public System.DateTime date { get; set; }
    }
}
