//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQScotion
    {
        public int Id { get; set; }
        public Nullable<int> QNo { get; set; }
        public string lynqtion { get; set; }
        public string lynqAns { get; set; }
        public string lynqrecters { get; set; }
        public string lynqwrongers { get; set; }
    }
}
