//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilynq.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trail_List
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string ExamID { get; set; }
        public string ProgStudy { get; set; }
        public string Code { get; set; }
        public string Grade { get; set; }
    }
}
