//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUq
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Emailadd { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Message { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Solved { get; set; }
    }
}
