//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQSchCalendar
    {
        public int Id { get; set; }
        public string LynQName { get; set; }
        public string LynQGroup { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> endd { get; set; }
        public string LynQEvent { get; set; }
        public string borderColor { get; set; }
        public string backgroundColor { get; set; }
    }
}
