//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQTradeChat
    {
        public int Id { get; set; }
        public int RealID { get; set; }
        public Nullable<int> Tradeid { get; set; }
        public string MessCom { get; set; }
        public Nullable<System.DateTime> Mesdate { get; set; }
        public string LynQFname { get; set; }
        public string LynQerimg { get; set; }
        public string LynQSch { get; set; }
        public string LynQSchimg { get; set; }
    }
}
