//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQQuizQue
    {
        public int Id { get; set; }
        public string LynQGrpName { get; set; }
        public string quizname { get; set; }
        public string lynqtion { get; set; }
        public string lynQAns { get; set; }
        public Nullable<int> lynqrect { get; set; }
        public Nullable<int> lynqrong { get; set; }
        public string lynqrecters { get; set; }
        public string lynqrongers { get; set; }
    }
}
