//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQGroup
    {
        public int Id { get; set; }
        public string LynQGpName { get; set; }
        public string GPAdmin { get; set; }
        public Nullable<System.DateTime> GPDate { get; set; }
        public string GrPurpose { get; set; }
    }
}
