//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQScoDetail
    {
        public int Id { get; set; }
        public string LynQName { get; set; }
        public string Type { get; set; }
        public string Year { get; set; }
        public string Course { get; set; }
        public string Descr { get; set; }
        public Nullable<int> Hrs { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Sec { get; set; }
    }
}
