//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQChatSetting
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string ChatSS { get; set; }
        public string ChatSL { get; set; }
        public string ChatSH { get; set; }
        public string ChatLL { get; set; }
        public string ChatLH { get; set; }
        public string ChatHH { get; set; }
    }
}
