//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQFriend
    {
        public int Id { get; set; }
        public int LynQId { get; set; }
        public string LynQer { get; set; }
        public string LynQee { get; set; }
        public System.DateTime LynQedDate { get; set; }
        public string LynQStatus { get; set; }
        public string LynQerPic { get; set; }
        public string LynQeePic { get; set; }
        public string LynQerFname { get; set; }
        public string LynQeeFname { get; set; }
    }
}
