//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQLectAssignCode
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string AssignedBy { get; set; }
        public string AssignedTo { get; set; }
        public string Code { get; set; }
        public string UqGrpName { get; set; }
        public string Program { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public string Levell { get; set; }
        public int Semester { get; set; }
        public string UploadStatus { get; set; }
    }
}
