//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQProgram
    {
        public int Id { get; set; }
        public string LynQSchool { get; set; }
        public string SchoolName { get; set; }
        public string DeptName { get; set; }
        public string ProgName { get; set; }
        public string LynQUserid { get; set; }
    }
}
