//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQRequirement
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string ReqType { get; set; }
        public string Levell { get; set; }
        public string Opera { get; set; }
        public string Premise { get; set; }
        public decimal Value { get; set; }
        public string Semester { get; set; }
    }
}
