//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LynQQuiz
    {
        public int Id { get; set; }
        public string LynQGrpName { get; set; }
        public string QuizName { get; set; }
        public Nullable<int> Submissions { get; set; }
        public Nullable<int> calid { get; set; }
        public Nullable<int> Hrs { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Sec { get; set; }
    }
}
