//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGrade
    {
        public int Id { get; set; }
        public string LynQSch { get; set; }
        public string GradeCode { get; set; }
        public string ExamID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Dept { get; set; }
        public string ProgStudy { get; set; }
        public string Optn { get; set; }
        public string Levell { get; set; }
        public string Study_type { get; set; }
        public string Acadyear { get; set; }
        public Nullable<int> Semester { get; set; }
        public string Code { get; set; }
        public string Course { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Grad { get; set; }
        public Nullable<decimal> Gp { get; set; }
        public Nullable<decimal> CMk { get; set; }
        public Nullable<decimal> EMk { get; set; }
        public Nullable<decimal> Mk { get; set; }
        public string Type { get; set; }
    }
}
