//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skulz
    {
        public int Id { get; set; }
        public string Schools { get; set; }
        public string LynQSchimg { get; set; }
        public string Abv { get; set; }
        public string UploadStatus { get; set; }
        public Nullable<int> Semester { get; set; }
        public string AcadYear { get; set; }
        public string Study_Type { get; set; }
        public string RenegadeChat { get; set; }
        public string ExaminationService { get; set; }
        public string AuthorDepts { get; set; }
        public string RegStatus { get; set; }
        public string SchName { get; set; }
        public string SetCourses { get; set; }
        public string SHS { get; set; }
    }
}
