//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public int LynQId { get; set; }
        public string state { get; set; }
        public string LastEntry { get; set; }
        public string Pic { get; set; }
        public string LynQSchName { get; set; }
        public string LynQSchPic { get; set; }
        public string LynQFriends { get; set; }
    }
}
