//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UqCoding
    {
        public int Id { get; set; }
        public Nullable<int> schid { get; set; }
        public string LynQSch { get; set; }
        public string Code { get; set; }
        public string Course { get; set; }
        public Nullable<int> Credit { get; set; }
        public string Dept { get; set; }
    }
}
